#!/bin/bash

# MyBankUML Database Setup Script
# This script helps you set up the MySQL database for MyBankUML

echo "=========================================="
echo "MyBankUML Database Setup"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Check if MySQL is installed
echo "Step 1: Checking MySQL installation..."
if command -v mysql &> /dev/null; then
    echo -e "${GREEN}✓ MySQL is installed${NC}"
    mysql --version
else
    echo -e "${RED}✗ MySQL is not installed${NC}"
    echo "Please install MySQL first:"
    echo "  macOS: brew install mysql"
    echo "  Linux: sudo apt-get install mysql-server"
    exit 1
fi
echo ""

# Step 2: Check if MySQL is running
echo "Step 2: Checking if MySQL server is running..."
if pgrep -x mysqld > /dev/null || pgrep -x mysqld_safe > /dev/null; then
    echo -e "${GREEN}✓ MySQL server is running${NC}"
else
    echo -e "${YELLOW}⚠ MySQL server is not running${NC}"
    echo "Attempting to start MySQL..."
    
    # Try to start MySQL (macOS)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew services start mysql 2>/dev/null || mysql.server start
    # Try to start MySQL (Linux)
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo systemctl start mysql 2>/dev/null || sudo service mysql start
    fi
    
    sleep 2
    if pgrep -x mysqld > /dev/null || pgrep -x mysqld_safe > /dev/null; then
        echo -e "${GREEN}✓ MySQL server started${NC}"
    else
        echo -e "${RED}✗ Could not start MySQL server${NC}"
        echo "Please start MySQL manually and run this script again"
        exit 1
    fi
fi
echo ""

# Step 3: Get MySQL credentials
echo "Step 3: MySQL Connection Details"
echo "-----------------------------------"
read -p "MySQL Username (default: root): " MYSQL_USER
MYSQL_USER=${MYSQL_USER:-root}

read -sp "MySQL Password: " MYSQL_PASS
echo ""
echo ""

# Step 4: Test connection
echo "Step 4: Testing MySQL connection..."
if mysql -u "$MYSQL_USER" -p"$MYSQL_PASS" -e "SELECT 1" &> /dev/null; then
    echo -e "${GREEN}✓ MySQL connection successful${NC}"
else
    echo -e "${RED}✗ MySQL connection failed${NC}"
    echo "Please check your username and password"
    exit 1
fi
echo ""

# Step 5: Create database
echo "Step 5: Creating database and tables..."
if [ -f "database/schema.sql" ]; then
    if mysql -u "$MYSQL_USER" -p"$MYSQL_PASS" < database/schema.sql 2>/dev/null; then
        echo -e "${GREEN}✓ Database 'mybankuml' created successfully${NC}"
    else
        echo -e "${YELLOW}⚠ Database might already exist or there was an error${NC}"
        echo "Checking if database exists..."
        if mysql -u "$MYSQL_USER" -p"$MYSQL_PASS" -e "USE mybankuml" &> /dev/null; then
            echo -e "${GREEN}✓ Database 'mybankuml' already exists${NC}"
        else
            echo -e "${RED}✗ Failed to create database${NC}"
            exit 1
        fi
    fi
else
    echo -e "${RED}✗ schema.sql file not found${NC}"
    exit 1
fi
echo ""

# Step 6: Verify tables
echo "Step 6: Verifying tables..."
TABLE_COUNT=$(mysql -u "$MYSQL_USER" -p"$MYSQL_PASS" -D mybankuml -e "SHOW TABLES;" 2>/dev/null | wc -l)
if [ "$TABLE_COUNT" -gt 1 ]; then
    echo -e "${GREEN}✓ Found $((TABLE_COUNT - 1)) tables in database${NC}"
    mysql -u "$MYSQL_USER" -p"$MYSQL_PASS" -D mybankuml -e "SHOW TABLES;" 2>/dev/null
else
    echo -e "${RED}✗ No tables found${NC}"
    exit 1
fi
echo ""

# Step 7: Create properties file
echo "Step 7: Creating database configuration file..."
if [ ! -f "src/main/resources/db.properties" ]; then
    cat > src/main/resources/db.properties << EOF
# Database Configuration
# Generated by setup_database.sh

db.url=jdbc:mysql://localhost:3306
db.username=$MYSQL_USER
db.password=$MYSQL_PASS
db.database=mybankuml
EOF
    echo -e "${GREEN}✓ Created db.properties file${NC}"
    echo "  Location: src/main/resources/db.properties"
else
    echo -e "${YELLOW}⚠ db.properties already exists${NC}"
    read -p "Overwrite? (y/n): " OVERWRITE
    if [ "$OVERWRITE" = "y" ] || [ "$OVERWRITE" = "Y" ]; then
        cat > src/main/resources/db.properties << EOF
# Database Configuration
# Generated by setup_database.sh

db.url=jdbc:mysql://localhost:3306
db.username=$MYSQL_USER
db.password=$MYSQL_PASS
db.database=mybankuml
EOF
        echo -e "${GREEN}✓ Updated db.properties file${NC}"
    fi
fi
echo ""

# Step 8: Add to gitignore
echo "Step 8: Updating .gitignore..."
if [ -f ".gitignore" ]; then
    if ! grep -q "db.properties" .gitignore; then
        echo "src/main/resources/db.properties" >> .gitignore
        echo -e "${GREEN}✓ Added db.properties to .gitignore${NC}"
    else
        echo -e "${GREEN}✓ db.properties already in .gitignore${NC}"
    fi
else
    echo "src/main/resources/db.properties" > .gitignore
    echo -e "${GREEN}✓ Created .gitignore${NC}"
fi
echo ""

# Summary
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Update QuickConnectionTest.java with your credentials"
echo "2. Compile: mvn clean compile (or javac)"
echo "3. Test: java -cp 'target/classes:target/dependency/*:libs/*' bank.QuickConnectionTest"
echo ""
echo "Your database connection details:"
echo "  URL: jdbc:mysql://localhost:3306"
echo "  Username: $MYSQL_USER"
echo "  Database: mybankuml"
echo "  Config file: src/main/resources/db.properties"
echo ""

